<a href="https://colab.research.google.com/github/Saiakashaya/DATA_SCIENCE/blob/main/GuassianNB_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install kaggle

In [17]:
!kaggle datasets download aravindpcoder/diabetes-dataset

Dataset URL: https://www.kaggle.com/datasets/aravindpcoder/diabetes-dataset
License(s): CC-BY-SA-4.0
100% 15.6k/15.6k [00:00<00:00, 42.1MB/s]



In [18]:
ls-ltr /content

total 56944
-rw-r--r-- 1 root root 22738154 Nov  8  2021 diabetes_binary_health_indicators_BRFSS2015.csv
-rw-r--r-- 1 root root  6347570 Nov  8  2021 diabetes_binary_5050split_health_indicators_BRFSS2015.csv
-rw-r--r-- 1 root root 22738151 Nov  8  2021 diabetes_012_health_indicators_BRFSS2015.csv
-rw-r--r-- 1 root root  6324278 Nov  8  2021 diabetes-health-indicators-dataset.zip
-rw-r--r-- 1 root root    27316 Aug 23  2023 healthcare-diabetes.zip
-rw-r--r-- 1 root root    98571 Aug 23  2023 Healthcare-Diabetes.csv
-rw-r--r-- 1 root root    15992 Nov 18  2023 diabetes-dataset.zip
drwxr-xr-x 1 root root     4096 Jun  4 13:32 sample_data/


In [19]:
!unzip diabetes-dataset.zip

Archive:  diabetes-dataset.zip
  inflating: Dataset of Diabetes .csv  


In [20]:
import pandas as pd
data=pd.read_csv("Dataset of Diabetes .csv")
data.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N


In [40]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=data)

https://docs.google.com/spreadsheets/d/11iYUNkz6j3lHpHkN6WlDy6C6YlgKVs9LGSsJf20DFUg/edit#gid=0


In [21]:
data.iloc[0]

,0
ID,502
No_Pation,17975
Gender,F
AGE,50
Urea,4.7
Cr,46
HbA1c,4.9
Chol,4.2
TG,0.9
HDL,2.4


In [22]:
print(data.isnull().sum())

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64


In [23]:
data.dropna(inplace=True)
data.drop_duplicates(inplace=True)

In [24]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   ID         1000 non-null   int64  
 1   No_Pation  1000 non-null   int64  
 2   Gender     1000 non-null   object 
 3   AGE        1000 non-null   int64  
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64  
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object 
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB
None


In [30]:
X=data["HbA1c"]
Y=data["CLASS"]

In [31]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(Y)

In [32]:
x=X.values.reshape(-1,1)

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=45)

In [34]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [43]:
import numpy as np
HbA1c_level=float(input("Enter your HbA1c Level:"))
new_HbA1c_level=np.array(HbA1c_level).reshape(-1,1)
print(new_HbA1c_level)
result=model.predict(new_HbA1c_level)
print(result)
print(le.inverse_transform(result))
if result==3:
  print("Diabetes confirm")
elif result==2:
  print("Pre-Diabetes")
else:
  print("No Diabetes")

Enter your HbA1c Level:6
[[6.]]
[2]
['P']
Pre-Diabetes


In [49]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,f1_score, recall_score
y_pred = model.predict(x_test)

Accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy: {Accuracy:.2f}")

Precision=precision_score(y_test,y_pred, average='weighted')
print(f"Precision: {Precision:.2f}")

Recall=recall_score(y_test,y_pred,average='weighted')
print(f"Recall: {Recall:.2f}")

f1=f1_score(y_test,y_pred, average='weighted')
print(f"F1 Score: {f1:.2f}")

cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n",cm)

Accuracy: 0.92
Precision: 0.93
Recall: 0.92
F1 Score: 0.93
Confusion Matrix:
 [[ 16   4   0   2   0]
 [  0   0   0   0   0]
 [  0   0   7   2   0]
 [  5   0   2 161   0]
 [  0   0   0   1   0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
