In [1]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 29.8 MB/s  0:00:00m0:00:010:01

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
a=25
a

25

In [6]:
a=34
b=9
print(a)
b

34


9

In [8]:
import numpy as np
marks = [78, 85, 92, 67, 88, 95]
arr = np.array(marks)
print("Mean =", np.mean(arr))
print("Maximum =", np.max(arr))
print("Minimum =", np.min(arr))

Mean = 84.16666666666667
Maximum = 95
Minimum = 67


In [9]:
print(np.zeros((4,4)))
print(np.ones((2,6)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [10]:
data = np.random.rand(4,4)
print(data)

[[0.2738013  0.05765336 0.28191624 0.99672496]
 [0.57042903 0.94431177 0.51131666 0.13208445]
 [0.27572107 0.95286211 0.84039299 0.22669702]
 [0.56921903 0.03373282 0.40896443 0.65773569]]


In [11]:
a = np.array([10,20,30,40,50,60,70,80,90,100,110,120])
b = np.reshape(a,(3,4))
print(b)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [12]:
a = np.arange(24).reshape(6,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [13]:
numbers = [12,15,18,21,24,27,30,33,36]
print(numbers[2:7])

[18, 21, 24, 27, 30]


In [14]:
a = np.array([10,20,30])
b = np.array([5,15,25])
print(a+b)

[15 35 55]


In [15]:
a = np.array([50,40,30])
b = np.array([10,15,20])
print(a-b)

[40 25 10]


In [16]:
a = np.array([2,4,6])
b = np.array([3,5,7])
print(a*b)

[ 6 20 42]


In [17]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [18]:
a = np.array([[2,4,6],
              [1,3,5]])
print(a.T)

[[2 1]
 [4 3]
 [6 5]]


In [19]:
values = [45,12,89,34,23,67]
print(np.sort(values))

[12 23 34 45 67 89]


In [20]:
a = np.array([10,20,30])
b = np.array([40,50,60])
print(np.concatenate((a,b)))

[10 20 30 40 50 60]


In [21]:
data = [2,2,5,7,7,9,1,1,3]
print(np.unique(data))

[1 2 3 5 7 9]


In [22]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
print(np.linspace(5,50,10))

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
